# =========================================================================
# CLOUD BUILD - ANSIBLE IAP DEPLOYMENT (LOCAL FILES)
# =========================================================================
# 
# This Cloud Build configuration runs Ansible deployments using local files
# instead of pulling from a git repository.
# 
# Usage: gcloud builds submit . --config=cloudbuild.yaml
# =========================================================================

# Use service account for all operations
serviceAccount: "projects/probable-cove-474504-p0/serviceAccounts/ansible-automation@probable-cove-474504-p0.iam.gserviceaccount.com"

# Required logging configuration when using custom service account
options:
  logging: "CLOUD_LOGGING_ONLY"
  dynamic_substitutions: true

steps:
  # Step 1: Verify target VM is accessible
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "=== Verifying Target VM ==="
        
        # Check who we're running as
        echo "Running as service account:"
        gcloud config get-value account || echo "No account set"
        
        # Check if VM exists and is running
        echo "Checking VM status..."
        VM_STATUS=$$(gcloud compute instances describe ${_TARGET_VM} \
          --zone=${_VM_ZONE} \
          --project=${PROJECT_ID} \
          --format="value(status)" 2>&1)
        VM_EXIT_CODE=$$?
        
        echo "VM Status query result: $$VM_STATUS"
        echo "Exit code: $$VM_EXIT_CODE"
        
        if [ $$VM_EXIT_CODE -ne 0 ]; then
          echo "ERROR: Failed to describe VM ${_TARGET_VM}"
          echo "Full error: $$VM_STATUS"
          exit 1
        fi
        
        if [ "$$VM_STATUS" != "RUNNING" ]; then
          echo "ERROR: VM ${_TARGET_VM} is not running. Status: $$VM_STATUS"
          exit 1
        fi
        
        echo "SUCCESS: VM ${_TARGET_VM} is running and accessible"

  # Step 2: Run Ansible deployment (combined to share Ansible installation)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        set -e  # Exit on any error
        
        echo "=== Setting up Ansible Environment ==="
        # Install pip first
        apt-get update -qq && apt-get install -y -qq python3-pip > /dev/null 2>&1
        
        # Install Ansible and dependencies
        python3 -m pip install --quiet ansible google-auth google-cloud-compute
        
        # Verify installation
        ansible --version
        echo "Ansible environment ready"
        echo ""
        
        echo "=== Retrieving SSH Key from Secret Manager ==="
        # Create SSH directory
        mkdir -p /root/.ssh
        
        # Retrieve the SSH private key from Secret Manager
        gcloud secrets versions access latest --secret="ansible-ssh-private-key" > /root/.ssh/ansible_key
        chmod 600 /root/.ssh/ansible_key
        
        echo "SSH key retrieved successfully"
        echo ""
        
        echo "=== Creating IAP Hosts File ==="
        # Create a hosts file using your personal SSH user (same as local setup)
        cat > hosts-cloudbuild.yml << 'EOFHOSTS'
        all:
          children:
            targets:
              hosts:
                ${_TARGET_VM}:
                  ansible_host: ${_TARGET_VM}
                  ansible_user: askcloudedge_gmail_com
                  ansible_ssh_common_args: >-
                    -o ProxyCommand="gcloud compute start-iap-tunnel ${_TARGET_VM} 22 
                    --listen-on-stdin --project=${PROJECT_ID} --zone=${_VM_ZONE}
                    --verbosity=warning" 
                    -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
                    -o IdentitiesOnly=yes
                    -o ConnectTimeout=30 -o ServerAliveInterval=30
                  ansible_ssh_private_key_file: /root/.ssh/ansible_key
                  ansible_python_interpreter: auto_silent
        EOFHOSTS
        
        echo "Created Cloud Build hosts file"
        cat hosts-cloudbuild.yml
        echo ""
        
        echo "=== Testing IAP Connectivity ==="
        echo "Testing Ansible ping..."
        timeout 120 ansible all -i hosts-cloudbuild.yml -m ping || {
          echo "ERROR: Failed to connect to ${_TARGET_VM} via IAP"
          echo "Troubleshooting info:"
          gcloud compute instances describe ${_TARGET_VM} --zone=${_VM_ZONE} --format="table(name,status,machineType.basename(),networkInterfaces[0].networkIP:label=INTERNAL_IP)"
          exit 1
        }
        echo "SUCCESS: IAP connectivity verified"
        echo ""
        
        echo "=== Executing Ansible Playbook: ${_PLAYBOOK} ==="
        # Show current directory and files
        echo "Playbooks directory:"
        ls -la playbooks/
        echo ""
        
        # Run the playbook using Cloud Build hosts file
        ansible-playbook -i hosts-cloudbuild.yml \
          playbooks/${_PLAYBOOK} \
          -v \
          --timeout=60 \
          --extra-vars "deployment_id=${BUILD_ID}" | tee deployment.log
        
        # Check if playbook succeeded
        if [ $${PIPESTATUS[0]} -ne 0 ]; then
          echo "ERROR: Playbook execution failed"
          echo ""
          echo "=== Last 50 lines of deployment log ==="
          tail -50 deployment.log
          exit 1
        fi
        echo "SUCCESS: Playbook ${_PLAYBOOK} completed successfully"
        echo ""
        
        echo "=== Running Post-Deployment Validation ==="
        # Copy validation scripts to VM
        ansible all -i hosts-cloudbuild.yml -m copy \
          -a "src=validation/ dest=/tmp/ mode='preserve'" || {
          echo "WARNING: Failed to copy validation scripts, skipping validation"
          exit 0
        }
        
        # Run validation
        ansible all -i hosts-cloudbuild.yml -m shell \
          -a "/tmp/validate_all.sh --verbose" \
          --become | tee validation.log || {
          echo "WARNING: Validation failed or incomplete"
        }
        
        # Show validation summary
        echo ""
        echo "=== Validation Summary ==="
        if grep -q "✅ ALL VALIDATIONS PASSED" validation.log; then
          echo "🎉 ALL VALIDATIONS PASSED!"
        elif grep -q "❌ VALIDATION FAILURES" validation.log; then
          echo "⚠️  SOME VALIDATIONS FAILED"
        else
          echo "ℹ️  VALIDATION INCOMPLETE OR MIXED RESULTS"
        fi
        
        echo ""
        echo "Last 20 lines of validation log:"
        tail -20 validation.log || echo "No validation log available"

# Substitution variables (can be overridden at runtime)
substitutions:
  _TARGET_VM: "ansible-rhel9-vm"
  _VM_ZONE: "us-central1-a"
  _PLAYBOOK: "golden-image-rhel9.yml"

# Build tags for identification
tags: ["ansible-local", "iap-deployment", "service-account"]

# Timeout for the entire build
timeout: "1800s"  # 30 minutes

# =========================================================================
# USAGE EXAMPLES:
# =========================================================================
#
# Basic deployment:
# gcloud builds submit . --config=cloudbuild.yaml
#
# Deploy different playbook:
# gcloud builds submit . --config=cloudbuild.yaml \
#   --substitutions=_PLAYBOOK=golden-image-rhel8.yml
#
# Deploy to different VM:
# gcloud builds submit . --config=cloudbuild.yaml \
#   --substitutions=_TARGET_VM=my-other-vm,_VM_ZONE=us-west1-a
#
# Deploy with multiple substitutions:
# gcloud builds submit . --config=cloudbuild.yaml \
#   --substitutions=_TARGET_VM=production-vm,_VM_ZONE=us-central1-b,_PLAYBOOK=golden-image-rhel9.yml
#
# =========================================================================


